### ISSUE TITLE
不会装（教我！）

### ISSUE THREAD

**Issue by D-6CF-X** [Cvandia/nonebot-plugin-fishspeech-tts#10]
运行无红字报错
用windows本地
![屏幕截图 2024-12-06 172158](https://github.com/user-attachments/assets/85d89872-077e-4fef-a808-baa12830ff0e)
机器人说 获取TTS音频失败, 检查API后端
用的fish-speech离线
运行start后弹这个后就没操作了
![image](https://github.com/user-attachments/assets/4b1ae8bf-ff8a-4bb6-97e9-7dea68105465)
![image](https://github.com/user-attachments/assets/0d49ce82-c2e5-4b6d-a004-6900249d9219)
配置txt
![image](https://github.com/user-attachments/assets/b897abf8-ce6e-4f16-a9b1-201ef145b6af)
配置env.
![屏幕截图 2024-12-06 171544](https://github.com/user-attachments/assets/14605d67-4b45-4332-9a04-19d8f73dba39)
用的本机
机器人端口不是8000（话说这个是不是监听地址）
反正试了几种组合都叫我检查api
能给个联系方式指导一下或者直接教吗

**Comment by Cvandia** [comment]
打开`http://127.0.0.1:8000`地址看看api服务是否工作正常

**Comment by Cvandia** [comment]
联系方式在readme.md的标签里哦
